version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - '5432:5432'
    volumes: 
      - ./dados_postgres:/var/lib/postgresql/data
volumes: 
  db:
    driver: local